# Generated by Django 2.2 on 2024-10-31 01:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CuentasZistemo',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('api_dev_key', models.TextField(default=None, max_length=255)),
                ('user', models.TextField(max_length=255)),
                ('password', models.TextField(default=None, max_length=255)),
                ('access_token', models.TextField(default=None, max_length=255)),
                ('expires_in', models.IntegerField(default=None)),
                ('refresh_token', models.TextField(default=None)),
                ('ultima_fecha_obtencion_token', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Proyectos',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('project_name', models.TextField(max_length=255)),
                ('number', models.TextField(max_length=255)),
                ('customer_name', models.TextField(blank=True, max_length=255, null=True)),
                ('status', models.TextField(blank=True, max_length=255, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Configuraciones',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('llave', models.TextField(max_length=255)),
                ('valor', models.TextField(max_length=255)),
                ('cuenta_zistemo', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='zistemo_automation_api.CuentasZistemo')),
            ],
        ),
    ]
