# Generated by Django 2.2 on 2024-10-31 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zistemo_automation_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuariosZistemo',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('zistemo_id', models.TextField(max_length=255)),
                ('first_name', models.TextField(max_length=255)),
                ('email', models.TextField(blank=True, max_length=255, null=True)),
                ('zistemo_activo', models.BooleanField(default=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
    ]
