# Generated by Django 2.2 on 2024-10-31 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zistemo_automation_api', '0002_usuarioszistemo'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarioszistemo',
            name='last_name',
            field=models.TextField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='usuarioszistemo',
            name='first_name',
            field=models.TextField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='usuarioszistemo',
            name='zistemo_id',
            field=models.TextField(default=None, max_length=255),
        ),
    ]
