# Generated by Django 2.2 on 2024-10-31 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zistemo_automation_api', '0003_auto_20241031_0219'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeEntries',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('zistemo_id', models.TextField(default=None, max_length=255)),
                ('user_id', models.TextField(default=None, max_length=255)),
                ('project_id', models.TextField(default=None, max_length=255)),
                ('hours', models.TextField(default=None, max_length=255)),
                ('notes', models.TextField(default=None, max_length=255)),
                ('billed', models.TextField(default=None, max_length=255)),
                ('hours_rounded', models.TextField(default=None, max_length=255)),
                ('projectName', models.TextField(default=None, max_length=255)),
                ('taskName', models.TextField(default=None, max_length=255)),
                ('userName', models.TextField(default=None, max_length=255)),
                ('customer_name', models.TextField(default=None, max_length=255)),
                ('log_date_formatted', models.TextField(default=None, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
