# Generated by Django 2.2 on 2024-10-31 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zistemo_automation_api', '0004_timeentries'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuentaszistemo',
            name='refresh_token',
        ),
    ]
