# Generated by Django 2.2 on 2024-10-31 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zistemo_automation_api', '0005_remove_cuentaszistemo_refresh_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuentaszistemo',
            name='expires_in',
        ),
        migrations.AddField(
            model_name='cuentaszistemo',
            name='expires',
            field=models.DateTimeField(default=None),
        ),
    ]
