# Generated by Django 2.2 on 2024-10-31 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zistemo_automation_api', '0006_auto_20241031_0559'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuentaszistemo',
            name='password',
        ),
        migrations.RemoveField(
            model_name='cuentaszistemo',
            name='user',
        ),
    ]
