# Generated by Django 2.2 on 2024-11-01 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zistemo_automation_api', '0007_auto_20241031_0601'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuentaszistemo',
            name='client_id',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
