# Generated by Django 2.2 on 2024-11-01 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zistemo_automation_api', '0008_cuentaszistemo_client_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyectos',
            name='project_id',
            field=models.TextField(default=None, max_length=255),
        ),
    ]
