# Generated by Django 2.2 on 2024-11-28 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zistemo_automation_api', '0009_proyectos_project_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeentries',
            name='csv_key',
            field=models.TextField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='timeentries',
            name='billed',
            field=models.TextField(blank=True, default='0', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='timeentries',
            name='notes',
            field=models.TextField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='timeentries',
            name='project_id',
            field=models.TextField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='timeentries',
            name='user_id',
            field=models.TextField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='timeentries',
            name='zistemo_id',
            field=models.TextField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
