# Generated by Django 2.2 on 2024-11-28 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zistemo_automation_api', '0010_auto_20241128_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeentries',
            name='time_entry_file_name',
            field=models.TextField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
